pipeline {
   agent any
      
        stages {

            stage('Checkout') {

                steps{
                    echo 'Pulling code from GitHub....' 

                }    

            } 

            stage('Install Dependencies') {

                steps{
                    echo 'Installing pyhton dependancies....'
                    sh 'pip3 install boto3 pytest'

                }    

            } 

            stage('Run Test') {

                steps{
                    echo 'Running the python test....'
                    sh 'python3 -m pytest python-programs/ -v || true'

                }    

            } 

            stage('Package Lambda') {

                steps{
                    echo 'Deploying to AWS Lambda.....'
                    sh '''
                         aws lambda update-function-code \
                             --function-name backup-notifier \
                             --zip-file fileb://lambda.zip \
                             --region us-east-1 || true
                         
                         '''

                }    

            }
            
             stage('Notify') {

                steps{
                    echo 'sending Notifications....'
                    sh 'echo pipeline completed successfully!'

                }    

            } 

        }

        post {
           success{
               echo 'Pipeline completed succesfully!'
           } 
           failure{
              echo 'Pipeline failed! check logs!'
           }
        }


}